# Generated by Django 3.2.15 on 2022-10-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220925_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'verbose_name': 'amount of ingredients', 'verbose_name_plural': 'amount of ingredients'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'shopping cart', 'verbose_name_plural': 'shopping cart'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'favorite', 'verbose_name_plural': 'favorite'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'tags of recipe', 'verbose_name_plural': 'tags of recipe'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe', verbose_name='favorite recipes'),
        ),
        migrations.AlterField(
            model_name='tagrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='recipe'),
        ),
        migrations.AlterField(
            model_name='tagrecipe',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='tag'),
        ),
    ]
