# Generated by Django 3.2.15 on 2022-10-05 17:36

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221005_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[recipes.validators.HexValidator(length=7)], verbose_name='tag colors'),
        ),
    ]
