# Generated by Django 3.2.15 on 2022-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220918_1503'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user_from', 'user_to'), name='unique_subscription'),
        ),
    ]
