# Generated by Django 3.2.15 on 2022-10-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': ('user',), 'verbose_name_plural': 'users'},
        ),
    ]
